#!/usr/bin/env python

import sys

from uwe_ipg_rqt.UWEIpgRobotSteeringGUI import UWEIpgRobotSteeringGUI
from rqt_gui.main import Main

plugin = 'uwe_ipg_rqt.UWEIpgRobotSteeringGUI.UWEIpgRobotSteeringGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
